image:
  - Ubuntu

environment:
  MINICONDA: C:\Miniconda3
install:
  # Get Miniconda and make it the main Python interpreter
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p ~/miniconda 
  - rm ~/miniconda.sh
  - export PATH=~/miniconda/bin:$PATH
  - conda env create -f environment.yml
  - source activate mini-wake
  - pip install codecov

build: false

test_script:
  - pytest --cov=./

on_finish:
  - codecov
  - cat coverage.xml
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name 'test-output.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    subject: 'Build {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false